# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branche', multiselectfield.db.fields.MultiSelectField(choices=[(b'Umzug', b'Umzug'), (b'Reinigung', b'Reinigung'), (b'Maler', b'Maler'), (b'Architekt', b'Architekt'), (b'Sanitaer', b'Sanitaer'), (b'Schreiner', b'Schreiner'), (b'Gartenbau', b'Gartenbau'), (b'Elektriker', b'Elektriker'), (b'Dachdecker', b'Dachdecker'), (b'Bodenbelaege', b'Bodenbelaege')], max_length=95, null=True)),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('plz', models.CharField(db_index=True, max_length=5, null=True)),
                ('ort', models.CharField(db_index=True, max_length=200, null=True)),
                ('strasse', models.CharField(max_length=200, null=True)),
                ('nr', models.CharField(max_length=200, null=True)),
                ('beschreibung', models.TextField()),
                ('eMail', models.EmailField(db_index=True, max_length=200, null=True)),
                ('homepage', models.CharField(db_index=True, max_length=200, null=True)),
                ('firm_logo', models.ImageField(db_index=True, upload_to=b'treasure_image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontaktanfrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('vorname', models.CharField(max_length=20, null=True)),
                ('eMail', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('beschreibung', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
