# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_base', '0002_delete_branchen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kontaktanfrage',
        ),
    ]
