# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fdx_mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmeneintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branche', multiselectfield.db.fields.MultiSelectField(choices=[('Umzug', 'Umzug'), ('Reinigung', 'Reinigung'), ('Maler', 'Maler'), ('Architekt', 'Architekt'), ('Sanit\xe4r', 'Sanit\xe4r'), ('Schreiner', 'Schreiner'), ('Gartenbau', 'Gartenbau'), ('Elektriker', 'Elektriker'), ('Dachdecker', 'Dachdecker'), ('Bodenbel\xe4ge', 'Bodenbel\xe4ge')], max_length=93)),
                ('nameAnsprechperson', models.CharField(db_index=True, max_length=200, null=True)),
                ('firmaName', models.CharField(db_index=True, max_length=200, null=True)),
                ('plz', models.IntegerField(db_index=True)),
                ('ort', models.CharField(db_index=True, max_length=200, null=True)),
                ('tel', models.CharField(db_index=True, max_length=200, null=True)),
                ('eMail', models.EmailField(db_index=True, max_length=200, null=True)),
                ('beschreibung', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
